### ISSUE TITLE
Nominator can't join its pool in Pools Overview page

### ISSUE THREAD

**Issue by frankli-dev** [polkadot-cloud/polkadot-staking-dashboard#1817]
Here are my steps.

1. There are two validators `Alice` & `Bob`
2. Using `Charlie`, I create a pool `AT 01` (selecting `Alice` & `Bob` as validators)
3. When creating a pool, I select `Ferdie` as a nominator.
4. After pool is created, if I select `Ferdie` account, the UI doesn't show any `Join` button as below
<img width="1028" alt="pools___Creditcoin" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/51565705/79bd4f05-0b7e-46d9-b667-87ff1ba2406c">

I think we should support Nominator can also join its pool on this page (pools/overview).

**Comment by rossbulat** [comment]
An upcoming nomination pool migration will mean that nominators will no longer be able to become a pool member. This will affect the dashboard UI - perhaps this issue is better suited to monitor this change instead.

The dashboard will need to make it obvious that it is not possible to join a pool or existing nominators. This could just entail a prompt on the Pools page along with disabled buttons.

**Comment by rossbulat** [comment]
Closing as the `Ferdie` account can join the pool in addition to being the nominator role.

What the dashboard is lacking currently is a dedicated UI for pool role accounts to carry out their roles.
