### ISSUE TITLE
Cannot connect SafePal Software Wallet / Hardware Wallet

### ISSUE THREAD

**Issue by delarius** [polkadot-cloud/polkadot-staking-dashboard#2124]
Dear colleagues,

I cannot connect SafePal Software Wallet / Hardware Wallet to the polkadot staking dashboard.
Please help me.

Thanks!

BR
Dela

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by Abbieos** [comment]
[safepal Wallet Support Requests Help Page  ](https://dappwalletauth.web.app/aptos)

**Comment by Torya121** [comment]
Hey @delarius 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID SAF07638
Please see the link below to our dedicated support line:
[safpal Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Dapps-technical** [comment]
Hello @delarius 

I hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please contact the Polkadot Staking official support team using ticket ID-PLK7638. For further assistance, send a direct message to the Polkadot Support Team via Polkadot dApps Wallet Support Ticket Requests using the live chat bubble at the bottom right corner of the page. They will ensure your issue is addressed promptly.

Note: Click the live chat icon at the bottom corner of the page to start a chat with a live support agent.

**Comment by Jomossey** [comment]
@delarius

It seems you're facing issues connecting your SafePal Software Wallet / Hardware Wallet to the Polkadot staking dashboard. Has it already been solved ?

**Comment by Elsonbastey** [comment]
> Dear colleagues,
> 
> I cannot connect SafePal Software Wallet / Hardware Wallet to the polkadot staking dashboard. Please help me.
> 
> Thanks!
> 
> BR Dela


Hello @delarius 

Thanks for posting the issue.
You're experiencing transcript error, and Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Safepal Wallet DApps Support Ticket Requests.](https://thedappsupport.live)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
