### ISSUE TITLE
Nomination pools info not displayed for Kusama

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-cloud/polkadot-staking-dashboard#2164]
The Kusama nomination pool that an account is a member of is not displayed:

Screenshot with a Kusama pool member connected as a read-only account:
Eynp4SsBk3ng8r4MZhnAznTgfpqvF27BfdVcxCT1qwkF7g3
![image](https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/120041850/6d56bf96-3fa0-43a9-9cfd-8d46976dcd5f)

Equivalent screenshot on Polkadot:
14i6reD45AFYSFUhADHY2Y1GPjjtigS5Ta18bAVhjH9qwCfY
![image](https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/120041850/3a75cf0d-e589-4ffb-910a-38d5a9caa059)

**Comment by mruepp** [comment]
Same issue here: 
![Screenshot 2024-07-03 at 22 04 30](https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/10906913/69c96210-0d73-4107-a855-23f429d056c7)

Same Account in Nova wallet staking shows Pool, claim, rewards, etc. perfectly fine

I am using talisman wallet for the web stakeboard

**Comment by mruepp** [comment]
Exactly same behavior here

**Comment by rossbulat** [comment]
Thanks for posting. The issue here is that the dashboard is still trying to get identity info from the relay chain, but the identities have recently been moved to a system chain called the People Chain. I have disabled identity fetching to get the pools functionality working again in https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2183, and will support the People Chain and identities again in a future PR.

Please let me know if there are further issues.
