### ISSUE TITLE
When in pool: unbonding inconsistency?

### ISSUE THREAD

**Issue by niklasp** [polkadot-cloud/polkadot-staking-dashboard#2189]
Clicking the two highlighted buttons triggers the same pallet + extrinsic.
<img width="1262" alt="Bildschirmfoto 2024-07-09 um 09 46 17" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/1685139/01638015-aa14-4099-935d-bd4d0e88b243">

Clicking the minus however states that 1 DOT must remain bonded, "Manage" -> "Leave Pool" lets me unbond all from a pool.

<img width="1024" alt="Bildschirmfoto 2024-07-09 um 09 43 17" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/1685139/c299b148-1f99-4967-b410-856383c88f9d">
<img width="1012" alt="Bildschirmfoto 2024-07-09 um 09 43 37" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/1685139/5ab7947e-3b3d-416d-a7cb-f25c82e270af">

Which one is correct?

**Comment by rossbulat** [comment]
This is by design, admittedly can cause confusion.

Unbond via Manage Unbond forces the minimum bond to stay in the pool, whereas Leave Pool assumes the member wants to unbond everything. 

I think the functionality is important but the UI could do a better job at explaining this to the user - perhaps provide a link to Leave Pool in the Unbond Modal if they do indeed want out of the pool
